project:
  type: website

website:
  description: "A blog built with Quarto"
  site-url: https://losnappas.github.io # you must change this appropriately for RSS feeds to work properly
  title: "losnappas blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/losnappas/blog
      - icon: twitter
        href: https://twitter.com/losnappas

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
